package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/tahkapaa/coke/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Car)
// DB Table: Plural (cars)
// Resource: Plural (Cars)
// Path: Plural (/cars)
// View Template Folder: Plural (/templates/cars/)

// CarsResource is the resource for the Car model
type CarsResource struct {
	buffalo.Resource
}

// List gets all Cars. This function is mapped to the path
// GET /cars
func (v CarsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	cars := &models.Cars{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Cars from the DB
	if err := q.All(cars); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, cars))
}

// Show gets the data for one Car. This function is mapped to
// the path GET /cars/{car_id}
func (v CarsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Car
	car := &models.Car{}

	// To find the Car the parameter car_id is used.
	if err := tx.Find(car, c.Param("car_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, car))
}

// New renders the form for creating a new Car.
// This function is mapped to the path GET /cars/new
func (v CarsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Car{}))
}

// Create adds a Car to the DB. This function is mapped to the
// path POST /cars
func (v CarsResource) Create(c buffalo.Context) error {
	// Allocate an empty Car
	car := &models.Car{}

	// Bind car to the html form elements
	if err := c.Bind(car); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(car)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, car))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Car was created successfully")

	// and redirect to the cars index page
	return c.Render(201, r.Auto(c, car))
}

// Edit renders a edit form for a Car. This function is
// mapped to the path GET /cars/{car_id}/edit
func (v CarsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Car
	car := &models.Car{}

	if err := tx.Find(car, c.Param("car_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, car))
}

// Update changes a Car in the DB. This function is mapped to
// the path PUT /cars/{car_id}
func (v CarsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Car
	car := &models.Car{}

	if err := tx.Find(car, c.Param("car_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Car to the html form elements
	if err := c.Bind(car); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(car)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, car))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Car was updated successfully")

	// and redirect to the cars index page
	return c.Render(200, r.Auto(c, car))
}

// Destroy deletes a Car from the DB. This function is mapped
// to the path DELETE /cars/{car_id}
func (v CarsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Car
	car := &models.Car{}

	// To find the Car the parameter car_id is used.
	if err := tx.Find(car, c.Param("car_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(car); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Car was destroyed successfully")

	// Redirect to the cars index page
	return c.Render(200, r.Auto(c, car))
}
