package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/tahkapaa/coke/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Horse)
// DB Table: Plural (horses)
// Resource: Plural (Horses)
// Path: Plural (/horses)
// View Template Folder: Plural (/templates/horses/)

// HorsesResource is the resource for the Horse model
type HorsesResource struct {
	buffalo.Resource
}

// List gets all Horses. This function is mapped to the path
// GET /horses
func (v HorsesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	horses := &models.Horses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Horses from the DB
	if err := q.All(horses); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, horses))
}

// Show gets the data for one Horse. This function is mapped to
// the path GET /horses/{horse_id}
func (v HorsesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Horse
	horse := &models.Horse{}

	// To find the Horse the parameter horse_id is used.
	if err := tx.Find(horse, c.Param("horse_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, horse))
}

// New renders the form for creating a new Horse.
// This function is mapped to the path GET /horses/new
func (v HorsesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Horse{}))
}

// Create adds a Horse to the DB. This function is mapped to the
// path POST /horses
func (v HorsesResource) Create(c buffalo.Context) error {
	// Allocate an empty Horse
	horse := &models.Horse{}

	// Bind horse to the html form elements
	if err := c.Bind(horse); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(horse)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, horse))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Horse was created successfully")

	// and redirect to the horses index page
	return c.Render(201, r.Auto(c, horse))
}

// Edit renders a edit form for a Horse. This function is
// mapped to the path GET /horses/{horse_id}/edit
func (v HorsesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Horse
	horse := &models.Horse{}

	if err := tx.Find(horse, c.Param("horse_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, horse))
}

// Update changes a Horse in the DB. This function is mapped to
// the path PUT /horses/{horse_id}
func (v HorsesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Horse
	horse := &models.Horse{}

	if err := tx.Find(horse, c.Param("horse_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Horse to the html form elements
	if err := c.Bind(horse); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(horse)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, horse))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Horse was updated successfully")

	// and redirect to the horses index page
	return c.Render(200, r.Auto(c, horse))
}

// Destroy deletes a Horse from the DB. This function is mapped
// to the path DELETE /horses/{horse_id}
func (v HorsesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Horse
	horse := &models.Horse{}

	// To find the Horse the parameter horse_id is used.
	if err := tx.Find(horse, c.Param("horse_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(horse); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Horse was destroyed successfully")

	// Redirect to the horses index page
	return c.Render(200, r.Auto(c, horse))
}
